### ISSUE TITLE
Bump to CasADi 3.6.6?

### ISSUE THREAD

**Issue by agriyakhetarpal** [conda-forge/casadi-feedstock#114]
### Comment:

Hi there! CasADi has released a fairly new [3.6.6 release](https://github.com/casadi/casadi/releases/tag/3.6.6), but I didn't notice any automated PRs for updating the version. I just wanted to reach out in case there has been a problem with the builds and, if there isn't, whether a release could be triggered manually through this feedstock. Thank you!

I can do this manually by opening an issue with `@conda-forge-admin, please update version`, but it's usually better if the recipe maintainers do that first :)

Additional context: We are updating to CasADi 3.6.6 for both our build-time and run-time dependency as we usually do when nearing a release, and I always check if the same versions for our dependencies are available on PyPI and conda-forge.

<hr>

xref: https://github.com/pybamm-team/PyBaMM/pull/4391

**Comment by agriyakhetarpal** [comment]
Oh, I added the backticks thinking that the bot would not be pinged if I did so – haha

**Comment by traversaro** [comment]
Hello @agriyakhetarpal, thanks for raising the issue. Sorry I was away last week and I did not see this issue. I am indeed not sure why the automatic update does not work in casadi, but I never looked into it. CasADi 3.6.6 has some nice new features that I was interested in enabling, see https://github.com/conda-forge/casadi-feedstock/issues/112 . It is ok to wait for 1/2 days so I can look into enabling the features, or you prefer that we releaze 3.6.6 as soon as possible and then enable the additional features later?

**Comment by agriyakhetarpal** [comment]
No worries, @traversaro! For an automatic update, I'm not sure why it doesn't work (or maybe it was disabled manually), but if you wish, you may enable the "automerge" feature to let the bot merge version update PRs if the tests pass – that _might_ bring it back. I do not mind the delay at all, absolutely, please continue with #115 if it's easy enough to enable BLASFEO.

**Comment by traversaro** [comment]
> For an automatic update, I'm not sure why it doesn't work (or maybe it was disabled manually), but if you wish, you may enable the "automerge" feature to let the bot merge version update PRs if the tests pass – that _might_ bring it back.

Unfortunately casadi does not have a lot of tests (either C++ or Python) that runs in the recipe, so to be honest I am not super-confident about automatically merging the version updates, I prefer always to double check manually in some downstream projects that instead have quite some tests using casadi, especially given casadi releases are not super-frequent.

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/casadi-feedstock/pull/115 .
