### ISSUE TITLE
@conda-forge-admin, please add user @agriyakhetarpal 

### ISSUE THREAD

**Issue by traversaro** [conda-forge/casadi-feedstock#119]
### Additional comment:

@conda-forge-admin, please add user @agriyakhetarpal

**Comment by agriyakhetarpal** [comment]
Weird, the bot hasn't commented yet or reacted to this PR – should we try again?

**Comment by traversaro** [comment]
I can do it manually this morning.

**Comment by traversaro** [comment]
I can do it manually this morning.

**Comment by traversaro** [comment]
Done in https://github.com/conda-forge/casadi-feedstock/pull/120 .
